### ISSUE TITLE
Rename `standard`?

### ISSUE THREAD

**Issue by privat** [nitlang/nit#1434]
I do not thing it is was good idea to name standard `standard` because it causes an ambiguity.
If one talks about the standard library of Nit, does one talk about `/lib` or about `/lib/standard`?

For instance, even http://nitlanguage.org/doc/stdlib/ it titled *Nit Standard Library* but in fact talks about `/lib` and not only about `/lib/standard`

One solution to avoid this communication issue is to rename the library `standard` as something else.

Some proposals

* use the name `nit` (like in java and other). but this does not completely solve  the communication issue. eg "`nit` is the default a library in the standard libraries of Nit."
* use the name `default` because it is the library that is imported by default.
* use the name `implicit` because it is the library that is implicitly imported.
* use the name `base` or `basic` because it is the basic library that contains basic classes and services.
* keep the name `standard` because this issue is just pure nitpicking.

**Comment by R4PaSs** [comment]
Ideally, http://nitlanguage.org/doc/stdlib/ should point to standard only, though right now since we lack packages, we tend to use anything in lib as part of standard.

This should be fixed once we have a proper package distribution system, hence the standard can keep its name imho, as all that is in lib should be hosted someplace else than the compiler itself

That, and some modules in lib could be migrated to standard once they have reached a certain maturity level, like socket for instance

**Comment by Morriar** [comment]
What about `core`?

My idea is the following:

* `core` library equals the current standard, it's the minimum and default set of functionnalities
* `standard`, is the set of core + some libraries maintained inside the nit project (because used within src for example), thus given in standard with Nit
* everything else is migrated to external package once we have a packet manager

**Comment by privat** [comment]
`core` is nice.

For @R4PaSs the other issue with standard is that "does this come bundled with nit in the standard install" or "does this is imported by default in standard Nit programs",

**Comment by privat** [comment]
Going once, going twice, sold!
