### ISSUE TITLE
create a .configure file for easy and painless installation 

### ISSUE THREAD

**Issue by macmata** [nitlang/nit#1948]
what not working ?
-  need to install suff manually. 

how should it work ?
 - .configure --prefix= MYPATH && make && make install

**Comment by privat** [comment]
a usual `configure` will not install dependencies for you. Our current `make` does what most configure+make does. The README and the website do tell you what you might need according to your OS.

The is no `install` target yet in the Makefile because Nit is still in heavy development and we do not encourage people to install it system-wide. However, everything is done to be usable from the work directory and binaries in the subdirectory bin/ can  be safely added to your PATH. In fact the script misc/nit_env.sh does that for you.

Do you have a specific install issue or error message that we can address?

**Comment by macmata** [comment]
> Do you have a specific install issue or error message that we can address?

No

The reason are indeed valid. 
Thank you.
