### ISSUE TITLE
tools in PATH for test engines?

### ISSUE THREAD

**Issue by privat** [nitlang/nit#2105]
Currently, it was expected that tools are not available in the PATH when the toaster run the regression tests or deploys the applications.
This causes the various scripts and makefiles to include relative paths to retrieve the correct tool in bin. eg https://github.com/nitlang/nit/blob/20f25d03aab0f075c2059343983d3023e7ad3138/benchmarks/markdown/engines/nitmd/Makefile#L17

The proposal (to discuss in the issue) is to assume that the nittools are available in the PATH.

Possible issues:
* users will not source or install `misc/nit_env.sh` (as instructed by the Makefile output) and fails to run the various makefiles in contrib
* users will have more than one nit install and will fail to work in one because their PATH is configured in the other
* I need to teach our integration toasters to register the tools in the PATH before doing their job.

Advantages:
* simpler scripts for maintainers and newcommers
* out-of-tree-compilant because project outside the repo will assume tools in the PATH

**Comment by ventilooo** [comment]
I' not sure to understand at 100%, all the possible issues.

However, I think once the nit language will reach the 1.0 version it will be possible to install nit with only the compiler and the standard library and some tools like nitpretty/nitdoc/etc...
In that case, the users will deal themselves with their regression tests or the deployment of their application.

I would encourage the 3rd option to resolve that issue, because that PATH issue is only in the nit main project.

**Comment by xymus** [comment]
I'm favorable to put them in the PATH and rely on it. The examples and makefiles would be so much cleaner. Plus, we could use it to use the tools of one repo to build the contribs of another repo.
