### ISSUE TITLE
popcorn routes badly handle trailing /

### ISSUE THREAD

**Issue by privat** [nitlang/nit#2175]
Compare

* http://tutorial.nitlanguage.org/Hello_World
* http://tutorial.nitlanguage.org/Hello_World/

The route is the same for both

    app.use("/:mission", tutorial.mission_handler)

But having both for the same path cause issues with relative url :(
I think that the present behavior is not POLA

**Comment by Morriar** [comment]
The problem is do we want to interpret `/` as a `/:mission` where `:mission` is empty. (this apply to your example with `/:mission/:foo` where `:mission` = `Hello_World` and `:foo` is empty.

There is two solutions here:

1. `/` matches `/` AND `/:mission` with `:mission` == ""
2. `/` matches ONLY `/` (popcorn impl.)

I specificallty made the choice to not match `/:mission` in this case for two reasons:
* less route overlap
* less client code since the client does not need to check `if req.param("mission").is_empty`

Another problem is the trailing slash, should we remove it or no?

Again, two solutions:
1. redirect `/Hello_World/` to `/Hello_World` with a 302 (nitcorn impl. if i'm correct)
2. do not do anything (popcorn impl.)

My solutions to this issue:
* redef the popcorn routing in your app to redirect trailing `/` with a 302
* add a `use_before` handler to redirect trailing `/` with a 302 (prefered solution)
