### ISSUE TITLE
Generalize a property after the fact

### ISSUE THREAD

**Issue by jcbrinfo** [nitlang/nit#2310]
As far as I know, we do not have a way in Nit to generalize a property in a refinement. For example, suppose we have the following first module:
```
class A
    fun foo: Int do return 42
end
```

Now, suppose we try to generalize the `foo` method by writing the following second module:
```
class X
    fun foo: Int is abstract
end
redef class A
    super X
end
class B
    super X
    redef fun foo do return 21
end
```

We will obviously end up with a name conflict between `A::foo` and `X::foo`. So, what should be written instead to promote the introduction of `foo` property to class `X`, without editing the first module?

**Comment by Morriar** [comment]
Just... why?

**Comment by jcbrinfo** [comment]
Generated code versus developer.

**Comment by privat** [comment]
The original refinement specification (in someone's PhD thesis) features property generalization and deals with the various conflicts.
It is not implemented in Nit (nor PRM) because:

* it is more complex to do than it seems. Find the potential generalizations is complex with refinement.
* we need a keyword to mark the generalization, and using the `redef` keyword for a generalization is not POLA.
* resulting name scheme is not NOPA. eg. the fullname of `foo` is `A::foo` therefore the call-sites `my_x.A::foo` and `my_b.A::foo` might be confusing since X and B are not subclasses of A.
* you are the first to ask for the feature, so this does not seems to be a high demand.

Honestly, I do not have the time (nor the motivation) to implement it.
I can propose you, as a workaround, to introduce a new property in the general class and bind it to the orignal property in the original class:

~~~nit
class X
    fun foo_x: Int is abstract
end
redef class A
    super X
    redef foo_x do return foo
end
class B
    super X
    redef fun foo_x do return 21
end
~~~

**Comment by jcbrinfo** [comment]
I was just wondering if there was something more elegant than this workaround. Thank you anyway.
