### ISSUE TITLE
DocUnits are not always recognized

### ISSUE THREAD

**Issue by jcbrinfo** [nitlang/nit#2403]
See <http://nitlanguage.org/doc/nitc/class_core__text__abstract_text__Text.html#core__text__abstract_text__Text__to_cmangle.definition>

**Comment by Morriar** [comment]
Here the problem is not `nitmd` but the [markdown spec](https://spec.commonmark.org/0.28/#list-items):

> The most important thing to notice is that the position of the text after the list marker determines how much indentation is needed in subsequent blocks in the list item.

In other words, according to the spec, the given example is interpreted as a list item containing a paragraph.

Try it on github:

~~~markdown
A list
* item 1
* item 2

    code line 1
    code line 2
~~~

Will render:

~~~html
<p>A list</p>
<ul>
<li>
<p>item 1</p>
</li>
<li>
<p>item 2</p>
<p>code line 1<br>
code line 2</p>
</li>
</ul>
~~~

You can also try it with the CommonMark implementation: https://spec.commonmark.org/dingus/?text=A%20list%0A*%20item%201%0A*%20item%202%0A%0A%20%20%20%20code%20line%201%0A%20%20%20%20code%20line%202

Because in the example the block code should not be in the list, I suggest to protect the code block with fences:

~~~~~~
A list
* item 1
* item 2

~~~
code line 1
code line 2
~~~
~~~~~~

Or to stop the list definition with a paragraph:

~~~~~~
A list
* item 1
* item 2

Examples:

    code line 1
    code line 2
~~~~~~
