### ISSUE TITLE
calculator example - wrong result for 9^4

### ISSUE THREAD

**Issue by rgh36167** [nitlang/nit#2561]
on Linux/32bit it displays "= --2147.483648" as result. Works fine for smaller numbers.

Can't see how this happens, but also sometimes get a message in the console saying "DataStore error at deserialization: Malformed JSON number"

**Comment by xymus** [comment]
It looks like the bug is caused by an integer overflow in `Float::to_precision`. The implementation of `to_precision` was simplified to support the interpreter a while back, but we could replace it now and fix this bug.

The JSON error is also a result of the same bug, the state is saved as --2147.483648 which causes a parsing error.

Thank you for reporting this bug!
