### ISSUE TITLE
Opportunity TODOs

### ISSUE THREAD

**Issue by R4PaSs** [nitlang/nit#811]
Opportunity should be merged soon (PR #796), but there's still some work to do on the software itself, in terms of UI and robustness/security before its official (semi-public) release :
* [x] Return to the meetup creation page when the creation fails (auto-complete fields with old info)
* [ ] Change the UI for answers to a Meetup, use real checkboxes instead of the V/X actual UI (still relevant ?)
* [x] Use real buttons for the addition/deletion of an attendee to a Meetup 
* [x] Forbid creation of a Meetup without at least one answer
* [ ] Option to modify a Meetup after its creation
* [ ] Add email field to people for notifications
* [ ] Beautify the UI
* [ ] Finish the REST API for eventual external clients
* [ ] Pass HTML W3C validation

**Comment by amineorion** [comment]
Je vais: 
1. Changer l'UI et utiliser un design plus modern comme Material design, on peut utiliser cette implémentation:  https://material.angularjs.org
2. Nit sera responsable de retourner les données en format JSON donc il y aura une partie backend 100% en Nit et partie frontend en angularJS ( c'est meilleur et ce qui est utilisé dans l'industrie et on peux avec ajouter une application mobile avec le même code )

**Comment by R4PaSs** [comment]
Salut,

Désolé pour la réponse tardive, moi ça me va !
Pour la partie Nit, va falloir la compléter un bon coup l'API REST, elle est plutôt light en ce moment, y'aura peut-être à retoucher au modèle par la même pour qu'il soit plus friendly avec l'API REST.

Pour l'UX, why not, ça peut pas faire de mal d'avoir un proto alternatif, s'il est plus utilisable/sexy/maintenable que l'actuel, ça le fait.

Après est-ce que tu comptes toucher aux autres TODO de la liste ? Y'aurait probablement de la job à faire sur le modèle, présentement il convient à peu près pour les besoins Latèce, mais pour une utilisation plus générale, on est encore à côté.

@xymus avait parlé un coup informellement d'un système de template pour les opportunités les plus fréquentes: meetups pour choisir une date/créneau horaire de rencontre, lieu de rencontre etc.
Ça pourrait rentrer dans les TODO éventuellement, je sais pas ce que les autres en pensent.

**Comment by amineorion** [comment]
Salut,

Oui je vais faire le TODO list, j'ai deux problèmes pour le moment:
1. Comment executer d'une façon générique une method dans une class comme en java il y a :
method = obj.getClass().getMethod(methodName)
method.invoke(obj,arg1)
2. Si je place mes fichiers dans des dossier comment je les import ?

**Comment by privat** [comment]
Salut.

1. on peut pas. Peux-tu montrer pourquoi t'as besoin de ça qu'on puisse proposer une alternative.
2. `import nomdumodule` cf. http://nitlanguage.org/manual/module/

**Comment by amineorion** [comment]
1. Pour le routing, je veux bien que tous les actions passent par une seule méthode et puis rediriger vers la bonne méthode donnée qui a été spécifier dans une classe de config
2.la visibilité de import nomdumodule et que les sur les fichiers dans le même dossier non ? je veux crée des module dans d'autre dossiers et les importer dans le cadre de l'app ( sa veux dire de n'importe quel autre fichier d'un autre dossier, par exemple si j'ai dossier models et un dossier controllers et dans un fichiers dans le dossier models et je veux importer un module d'un fichier dans le dossier controllers, sa marche pas.

**Comment by amineorion** [comment]
So i managed to some other trick in the first problem, here the code https://gist.github.com/amineorion/1de527387aab8096e4fc
my problem as i commented there, i really have to hardcode some things and to rewrite useless code ( routing function) do you have in mind anything can solve that problem ? ty

**Comment by privat** [comment]
I am not sure I understand what you are trying to do.

First, nitcorn has already a routing framework, it is the point of the Route and Action classes. So I do not see what kind of issue you try to solve by adding a second level of controller, as you did with the `routing` method. Why you do not use the `answer` method, it is its job?

Second, the design of method `routing` and the three subclasses of `Action` seems fishy. But since I do not get the point, maybe the level of fishiness is fine but I suspect some kind of over-engineering : 3 classes and complex method orchestration.

Maybe you could try to explain **what** you are trying to achieve before showing us **how**, so our remarks can be more useful.

**Comment by amineorion** [comment]
So if I use the answer method, i really have to create a new class for every action, i think this is really verbose. What i want to do later that i can do a kind of interceptors for multiple reason, and the main reason of doing that, i want to create Opportunity as project maybe to start a web framework creating in Nit, and it need be as good as others in the market.

**Comment by privat** [comment]
OK, so if I get it, what you want is to have a single class with a specific method by service, the issue is then how to route the `action` to the correct specific method.
Bonus: having each service in its own module to better separate concerns.

The usual pattern to achieve this in Nit is to code a class per service. 
Note that classes in Nit are cheap and less verbose than in Java.
Then instantiate each class and register the object in some global controller (there is many way to do that, with pros and cons according the level of configuration you whant).

If you really want to have a single object and a method by service, I think that you are right to use a selection mechanism as you did with `routing`, I see no other way right now

In other languages you can use some kind of meta-programming to dynamically discover and select the correct method, so now I see the link with the first question related do `getMethod` (but meta-programming has a lot of drawbacks in this case).
In fact, if you thing about the `getMethod` way, it is analogous to the an-object-per-service way, where the method object represents the associated service. The difference is that these method objects are already created and registered, so less verbosity.

I need to leave now but I will think about how to simplify and factorize the `routing` method but I suspect that any level of improvement will require to model each service with some kind of data, so in a OO language it means manipulate each service with an object (with an associated class).

**Comment by amineorion** [comment]
well even cheap but if i want to create a REST service, i have to deal with around 4 basic actions for every entity, means that i have to copy paste a lot, especially when I m dealing with a large apps.
But i think i will do it with the Nit way, and we can see later.

**Comment by amineorion** [comment]
I did it with Nit way ( having each action in their own class ) and it seams a lot more clean, and I m not having any problem for now, I finished the Meetup REST API ( controller and model ) but the problem now that i don't understand the idea behind the app, what i got is: it is an app where any user can add meetups, and put the title , when and where + other opportunity that you can gain when you go to that meetup, and then anyone can see all meetups and modify or delete them ( this is what i see here http://opportunity.gresil.org/ ) but there is the code people and answer, can anyone explain please, thanks

**Comment by privat** [comment]
opportunity is a meetup planner/simple survey wabapp like doodle or framadate. We use it to plan meetups and select pizza topping. So it is a highly critical business application :)

**Comment by amineorion** [comment]
ok, i changed a lot on the opportunity code and i wanted to confirm are ppl are ok with changes, I discovered some problems while sending json object in POST and other issues anyway, i wanted to confirm is this code good enough or i have to do some changes before i continue doing opportunity, i did add some frontend but not well designed yet, i will improve a lot of UI. and fix other things on backend stuff. ( only create meetup and delete are working in UI right now ) here is the link for the repo i created https://github.com/amineorion/opportunity , thanks.

**Comment by R4PaSs** [comment]
Hi,

If you made changes that you want to share to us, especially if you request for comments, please do it through a Pull-Request, that's probably the best way to ask for feedback to the community, and if your code is valid, we can merge it ASAP so everyone can enjoy it faster :)

**Comment by xymus** [comment]
I'm with @R4PaSs, please work with a fork of the Nit language and modify opportunity in contrib/opportunity. You can then point us to a branch or make a pull request. 

You will also need a full fork because the Web framework used by Opportunity is located at lib/nitcorn. Feel free to study and improve it, most of its clients are in the contrib directory.

**Comment by amineorion** [comment]
Ok sorry for the delay, here is the pull request https://github.com/privat/nit/pull/1181

**Comment by xymus** [comment]
This issue is replaced by #1833.
